### Site metadata ###

site_name: GLADOS USER DOC
site_description: User doc for SPICE/GLADOS compiler
# site_url: https://michaelcurrin.github.io/mkdocs-quickstart/
site_url: https://etib-corp.github.io/SPICE/

repo_url: https://etib-corp.github.io/SPICE/
edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      # - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      # - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      # - Deploy: tutorial/deploy.md
