name: Deploy SPICE site

on:
  push:
    branches:
      - main
      - 17-feat-host-docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Deploy to GitHub Pages
        # run: mkdocs gh-deploy --force
        run: |
          mkdocs build --config-file docs/mkdocs.yml
          mkdocs gh-deploy --config-file docs/mkdocs.yml --force
