name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the project using make
      - name: Build with make
        run: make

      # Save the build artifact
      - name: Save build artifact
        run: ls -R && mkdir -p dist && mv .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe dist/
        # Replace <your_build_output_file> with the actual file name from your Makefile

      # Upload the artifact for the release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a GitHub release and attach artifacts
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/<your_build_output_file>
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release includes the following build:
            - Build file: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe
        # Replace <your_build_output_file> with your actual file name
