name: Build and Release

on:
  push:
    branches:
      - main # Adjust to the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

        # Read version from the VERSION file
      - name: Read version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Save the build artifact
      - name: Save build artifact
        run: make && ls -R && mkdir -p dist && mv .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe dist/
        # Replace <your_build_output_file> with the actual file name from your Makefile

      # Upload the artifact for the release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

 # Create a GitHub release and attach artifacts
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/<your_build_output_file>
          tag: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          body: |
            This release includes the following build:
            - Build file: <your_build_output_file>
        # Replace <your_build_output_file> with your actual file name
