name: Build and Release

on:
  push:
    branches:
      - main # Adjust to the branch you want to trigger on

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: make tests_run

  build:
    runs-on: ubuntu-latest
    needs: ["tests"]
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make

