name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: make tests_run

  release:
    runs-on: ubuntu-latest
    needs: ["build", "test"]
    steps:
    - name: Extract Tag or Branch Name
      id: extract_ref
      run: echo "ref_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact
        path: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Upload Release Asset to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe
        asset_name: artifact-name
        asset_content_type: application/octet-stream
