name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up a build environment
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build the project using make
      - name: Build with make
        run: make

      # Save the build artifact
      - name: Save build artifact
        run: mkdir -p dist && mv .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe dist/
        # Replace <your_build_output_file> with the actual file name from your Makefile

      # Upload the artifact for the release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/
=======
    - uses: actions/checkout@v4

    - name: Build
      run: make

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: make tests_run
>>>>>>> 584900caf487106c444c2dc1f2ba1682d1612554

  release:
    needs: build
    runs-on: ubuntu-latest
<<<<<<< HEAD

=======
    needs: ["build", "test"]
>>>>>>> 584900caf487106c444c2dc1f2ba1682d1612554
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
      # Create a GitHub release and attach artifacts
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/<your_build_output_file>
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release includes the following build:
            - Build file: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe
        # Replace <your_build_output_file> with your actual file name
=======
    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact
        path: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Upload Release Asset to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.10.3.0/build/spice-exe/spice-exe
        asset_name: artifact-name
        asset_content_type: application/octet-stream
>>>>>>> 584900caf487106c444c2dc1f2ba1682d1612554
